# Generated by Django 3.2.3 on 2021-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, upload_to='imgs/%d/%m/%Y/'),
        ),
    ]
